"""
Example of LLM supply chain vulnerabilities in a pizza shop application.

This module demonstrates how LLMs can introduce supply chain vulnerabilities
when used to generate or modify code without proper security controls.
"""

from flask import render_template, request, jsonify
import re
import os
import subprocess
import sys

# VULNERABILITY: Using LLM to directly generate and execute code
# This is a dangerous practice as LLMs may generate insecure code

class PizzaSupplyManager:
    """
    Manages pizza ingredients and suppliers.
    Contains intentional vulnerabilities related to LLM code generation.
    """
    
    def __init__(self):
        self.suppliers = {
            "Cheese Depot": {"rating": 4.5, "items": ["mozzarella", "parmesan", "ricotta"]},
            "Tomato Haven": {"rating": 4.8, "items": ["tomatoes", "tomato sauce"]},
            "Flour Mill Co.": {"rating": 4.2, "items": ["flour", "yeast"]},
            "Veggie Paradise": {"rating": 4.6, "items": ["peppers", "onions", "mushrooms"]},
            "Meat Market": {"rating": 4.4, "items": ["pepperoni", "sausage", "ham"]}
        }
        
        self.inventory = {
            "mozzarella": 50,
            "parmesan": 20,
            "ricotta": 15,
            "tomatoes": 40,
            "tomato sauce": 35,
            "flour": 100,
            "yeast": 25,
            "peppers": 30,
            "onions": 40,
            "mushrooms": 35,
            "pepperoni": 45,
            "sausage": 30,
            "ham": 25
        }
    
    def get_suppliers(self):
        """Return all suppliers and their information."""
        return self.suppliers
    
    def get_inventory(self):
        """Return current inventory levels."""
        return self.inventory
    
    def update_inventory(self, item, quantity):
        """Update inventory for a specific item."""
        if item in self.inventory:
            self.inventory[item] = quantity
            return True
        return False
    
    # VULNERABILITY: Using LLM to generate code that processes user input
    # without proper validation
    def process_order_report(self, report_query):
        """
        Process a report query about orders.
        VULNERABLE: This function uses an LLM to generate and execute code based on user input.
        """
        try:
            # Simulate an LLM generating code from user input
            # In a real scenario, this would be sent to an LLM API
            generated_code = self._simulate_llm_code_generation(report_query)
            
            # VULNERABILITY: Directly executing generated code
            # Never do this in production!
            result = {}
            exec(generated_code, {"inventory": self.inventory, "suppliers": self.suppliers, "result": result})
            return {"status": "success", "data": result}
        except Exception as e:
            return {"status": "error", "message": str(e)}
    
    def _simulate_llm_code_generation(self, query):
        """
        Simulates an LLM generating Python code based on a user query.
        
        This is a simplified simulation. In reality, this would send the query
        to an actual LLM API and get back generated code.
        """
        # Convert query to lowercase for easier matching
        query = query.lower()
        
        # VULNERABILITY: Code generation without proper validation or sanitization
        if "list all suppliers" in query:
            return """
result['suppliers'] = list(suppliers.keys())
"""
        elif "inventory count" in query:
            return """
result['inventory_count'] = len(inventory)
result['total_items'] = sum(inventory.values())
"""
        elif "low stock" in query:
            return """
result['low_stock'] = [item for item, quantity in inventory.items() if quantity < 30]
"""
        elif "supplier for" in query:
            # Extract the ingredient the user is asking about
            match = re.search(r"supplier for (\w+)", query)
            if match:
                ingredient = match.group(1)
                return f"""
result['suppliers_for_{ingredient}'] = [name for name, data in suppliers.items() if "{ingredient}" in data['items']]
"""
            
        # VULNERABILITY: Allowing arbitrary system access through code generation
        elif "system" in query or "os" in query or "exec" in query or "subprocess" in query:
            # Generate dangerous code that could lead to system access
            # This simulates an LLM generating unsafe code
            command = query.replace("run", "").replace("system", "").replace("command", "").strip()
            return f"""
# This is dangerous code that would be generated by an uncontrolled LLM
import os
result['system_info'] = os.popen('{command}').read()
"""
        
        # Default response if no pattern matches
        return """
result['message'] = 'Could not generate a report for that query'
"""

def handle_supply_chain_query(query):
    """
    Handle queries about the pizza supply chain.
    This is the function that would be exposed to the web application.
    """
    manager = PizzaSupplyManager()
    return manager.process_order_report(query)

# Secure alternative implementation
class SecurePizzaSupplyManager:
    """
    A secure implementation of the PizzaSupplyManager that doesn't use LLM-generated code execution.
    """
    
    def __init__(self):
        # Same initialization as the vulnerable version
        self.suppliers = {
            "Cheese Depot": {"rating": 4.5, "items": ["mozzarella", "parmesan", "ricotta"]},
            "Tomato Haven": {"rating": 4.8, "items": ["tomatoes", "tomato sauce"]},
            "Flour Mill Co.": {"rating": 4.2, "items": ["flour", "yeast"]},
            "Veggie Paradise": {"rating": 4.6, "items": ["peppers", "onions", "mushrooms"]},
            "Meat Market": {"rating": 4.4, "items": ["pepperoni", "sausage", "ham"]}
        }
        
        self.inventory = {
            "mozzarella": 50,
            "parmesan": 20,
            "ricotta": 15,
            "tomatoes": 40,
            "tomato sauce": 35,
            "flour": 100,
            "yeast": 25,
            "peppers": 30,
            "onions": 40,
            "mushrooms": 35,
            "pepperoni": 45,
            "sausage": 30,
            "ham": 25
        }
    
    def process_order_report(self, report_query):
        """
        Process a report query about orders - SECURE implementation.
        Uses predefined functions instead of generating and executing code.
        """
        query = report_query.lower()
        
        if "list all suppliers" in query:
            return {"status": "success", "data": {"suppliers": list(self.suppliers.keys())}}
            
        elif "inventory count" in query:
            return {
                "status": "success", 
                "data": {
                    "inventory_count": len(self.inventory),
                    "total_items": sum(self.inventory.values())
                }
            }
            
        elif "low stock" in query:
            low_stock = [item for item, quantity in self.inventory.items() if quantity < 30]
            return {"status": "success", "data": {"low_stock": low_stock}}
            
        elif "supplier for" in query:
            match = re.search(r"supplier for (\w+)", query)
            if match:
                ingredient = match.group(1)
                suppliers_for_item = [
                    name for name, data in self.suppliers.items() 
                    if ingredient in data["items"]
                ]
                return {
                    "status": "success", 
                    "data": {f"suppliers_for_{ingredient}": suppliers_for_item}
                }
        
        # SECURITY: Reject system commands entirely
        elif any(keyword in query for keyword in ["system", "os", "exec", "subprocess"]):
            return {
                "status": "error", 
                "message": "System commands are not allowed in reports"
            }
            
        # Default response
        return {
            "status": "error", 
            "message": "Unknown report type requested"
        }

def handle_secure_supply_chain_query(query):
    """
    Secure handler for supply chain queries.
    """
    manager = SecurePizzaSupplyManager()
    return manager.process_order_report(query)

# Example route handler for Flask
def supply_chain_endpoint():
    """
    Example Flask route handler for the supply chain vulnerability demo.
    """
    if request.method == 'POST':
        query = request.form.get('query', '')
        use_secure = request.form.get('secure', 'false') == 'true'
        
        if use_secure:
            result = handle_secure_supply_chain_query(query)
        else:
            result = handle_supply_chain_query(query)
            
        return jsonify(result)
    
    return render_template('supply_chain.html')